// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLNET
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"ProductID")]
            public float ProductID { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Name")]
            public string Name { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"ProductNumber")]
            public string ProductNumber { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"MakeFlag")]
            public bool MakeFlag { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"FinishedGoodsFlag")]
            public bool FinishedGoodsFlag { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Color")]
            public string Color { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"SafetyStockLevel")]
            public float SafetyStockLevel { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"ReorderPoint")]
            public float ReorderPoint { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"StandardCost")]
            public float StandardCost { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"ListPrice")]
            public float ListPrice { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"Size")]
            public string Size { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"SizeUnitMeasureCode")]
            public string SizeUnitMeasureCode { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"WeightUnitMeasureCode")]
            public string WeightUnitMeasureCode { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"Weight")]
            public float Weight { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"DaysToManufacture")]
            public float DaysToManufacture { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"ProductLine")]
            public string ProductLine { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"Class")]
            public string Class { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"Style")]
            public string Style { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"ProductSubcategoryID")]
            public float ProductSubcategoryID { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"ProductModelID")]
            public float ProductModelID { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"SellStartDate")]
            public DateTime SellStartDate { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"SellEndDate")]
            public DateTime SellEndDate { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"DiscontinuedDate")]
            public DateTime DiscontinuedDate { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"rowguid")]
            public string Rowguid { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"ModifiedDate")]
            public DateTime ModifiedDate { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"ProductID")]
            public float ProductID { get; set; }

            [ColumnName(@"Name")]
            public float[] Name { get; set; }

            [ColumnName(@"ProductNumber")]
            public float[] ProductNumber { get; set; }

            [ColumnName(@"MakeFlag")]
            public float[] MakeFlag { get; set; }

            [ColumnName(@"FinishedGoodsFlag")]
            public float[] FinishedGoodsFlag { get; set; }

            [ColumnName(@"Color")]
            public float[] Color { get; set; }

            [ColumnName(@"SafetyStockLevel")]
            public float SafetyStockLevel { get; set; }

            [ColumnName(@"ReorderPoint")]
            public float ReorderPoint { get; set; }

            [ColumnName(@"StandardCost")]
            public float StandardCost { get; set; }

            [ColumnName(@"ListPrice")]
            public float ListPrice { get; set; }

            [ColumnName(@"Size")]
            public float[] Size { get; set; }

            [ColumnName(@"SizeUnitMeasureCode")]
            public float[] SizeUnitMeasureCode { get; set; }

            [ColumnName(@"WeightUnitMeasureCode")]
            public float[] WeightUnitMeasureCode { get; set; }

            [ColumnName(@"Weight")]
            public float Weight { get; set; }

            [ColumnName(@"DaysToManufacture")]
            public float DaysToManufacture { get; set; }

            [ColumnName(@"ProductLine")]
            public float[] ProductLine { get; set; }

            [ColumnName(@"Class")]
            public float[] Class { get; set; }

            [ColumnName(@"Style")]
            public float[] Style { get; set; }

            [ColumnName(@"ProductSubcategoryID")]
            public float ProductSubcategoryID { get; set; }

            [ColumnName(@"ProductModelID")]
            public float ProductModelID { get; set; }

            [ColumnName(@"SellStartDate")]
            public DateTime SellStartDate { get; set; }

            [ColumnName(@"SellEndDate")]
            public DateTime SellEndDate { get; set; }

            [ColumnName(@"DiscontinuedDate")]
            public DateTime DiscontinuedDate { get; set; }

            [ColumnName(@"rowguid")]
            public float[] Rowguid { get; set; }

            [ColumnName(@"ModifiedDate")]
            public DateTime ModifiedDate { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
