// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using Microsoft.ML;
using System.Data.SqlClient;
using Microsoft.ML.Data;

namespace MLNET
{
    public partial class MLModel
    {
        public const string RetrainConnectionString = @"Data Source=.;Initial Catalog=AdventureWorks2019;Integrated Security=True";
        public const string RetrainCommandString = @"SELECT CAST([ProductID] as REAL), CAST([Name] as NVARCHAR(MAX)), CAST([ProductNumber] as NVARCHAR(MAX)), [MakeFlag], [FinishedGoodsFlag], CAST([Color] as NVARCHAR(MAX)), CAST([SafetyStockLevel] as REAL), CAST([ReorderPoint] as REAL), CAST([StandardCost] as REAL), CAST([ListPrice] as REAL), CAST([Size] as NVARCHAR(MAX)), CAST([SizeUnitMeasureCode] as NVARCHAR(MAX)), CAST([WeightUnitMeasureCode] as NVARCHAR(MAX)), CAST([Weight] as REAL), CAST([DaysToManufacture] as REAL), CAST([ProductLine] as NVARCHAR(MAX)), CAST([Class] as NVARCHAR(MAX)), CAST([Style] as NVARCHAR(MAX)), CAST([ProductSubcategoryID] as REAL), CAST([ProductModelID] as REAL), [SellStartDate], [SellEndDate], [DiscontinuedDate], CAST([rowguid] as NVARCHAR(MAX)), [ModifiedDate] FROM [Production].[Product]";

        /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="connectionString">Connection string for databases on-premises or in the cloud.</param>
        /// <param name="commandText">Command string for selecting training data.</param>
        public static void Train(string outputModelPath, string connectionString = RetrainConnectionString, string commandText = RetrainCommandString)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromDatabase(mlContext, connectionString, commandText);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a database source.For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="connectionString">Connection string for databases on-premises or in the cloud.</param>
        /// <param name="commandText">Command string for selecting training data.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromDatabase(MLContext mlContext, string connectionString, string commandText)
        {
            DatabaseLoader loader = mlContext.Data.CreateDatabaseLoader<ModelInput>();
            DatabaseSource dbSource = new DatabaseSource(SqlClientFactory.Instance, connectionString, commandText);

            return loader.Load(dbSource);
        }

        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"MakeFlag", @"MakeFlag"),new InputOutputColumnPair(@"FinishedGoodsFlag", @"FinishedGoodsFlag"),new InputOutputColumnPair(@"Color", @"Color"),new InputOutputColumnPair(@"Size", @"Size"),new InputOutputColumnPair(@"SizeUnitMeasureCode", @"SizeUnitMeasureCode"),new InputOutputColumnPair(@"WeightUnitMeasureCode", @"WeightUnitMeasureCode"),new InputOutputColumnPair(@"ProductLine", @"ProductLine"),new InputOutputColumnPair(@"Class", @"Class"),new InputOutputColumnPair(@"Style", @"Style"),new InputOutputColumnPair(@"rowguid", @"rowguid")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"ProductID", @"ProductID"),new InputOutputColumnPair(@"ReorderPoint", @"ReorderPoint"),new InputOutputColumnPair(@"StandardCost", @"StandardCost"),new InputOutputColumnPair(@"ListPrice", @"ListPrice"),new InputOutputColumnPair(@"Weight", @"Weight"),new InputOutputColumnPair(@"DaysToManufacture", @"DaysToManufacture"),new InputOutputColumnPair(@"ProductSubcategoryID", @"ProductSubcategoryID"),new InputOutputColumnPair(@"ProductModelID", @"ProductModelID")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Name",outputColumnName:@"Name"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"ProductNumber",outputColumnName:@"ProductNumber"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"MakeFlag",@"FinishedGoodsFlag",@"Color",@"Size",@"SizeUnitMeasureCode",@"WeightUnitMeasureCode",@"ProductLine",@"Class",@"Style",@"rowguid",@"ProductID",@"ReorderPoint",@"StandardCost",@"ListPrice",@"Weight",@"DaysToManufacture",@"ProductSubcategoryID",@"ProductModelID",@"Name",@"ProductNumber"}))      
                                    .Append(mlContext.Regression.Trainers.Sdca(new SdcaRegressionTrainer.Options(){L1Regularization=1F,L2Regularization=0.1F,LabelColumnName=@"SafetyStockLevel",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
 }
